name: location
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    volumes:
      - /tank/location/mosquitto/data:/mosquitto/data
      - /tank/location/mosquitto/log:/mosquitto/log
      # - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - "18831:1883"    # Changed host port to 18831
      - "9011:9001"    # Changed host port to 90011
    restart: unless-stopped
    networks:
      - batserver_docker_network

  owntracks-recorder:
    image: owntracks/recorder:latest
    container_name: owntracks-recorder
    environment:
      - OTR_HOST=0.0.0.0
      - OTR_PORT=8083
      - OTR_MQTT_HOST=mosquitto
      - OTR_MQTT_PORT=1883
      # Enable InfluxDB integration
      - OTR_INFLUXDB_URL=http://influxdb:8086
      - OTR_INFLUXDB_DB=${INFLUXDB_DB}
      - OTR_INFLUXDB_USER=${INFLUXDB_ADMIN_USER}
      - OTR_INFLUXDB_PASS=${INFLUXDB_ADMIN_PASSWORD}
    depends_on:
      - mosquitto
      - influxdb
    ports:
      - "8831:8083"    # Changed host port to 80831
    volumes:
      - /tank/location/owntracks-recorder:/store
    restart: unless-stopped
    networks:
      - batserver_docker_network

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    ports:
      - "8861:8086"    # Changed host port to 80861
    volumes:
      - /tank/location/influxdb:/var/lib/influxdb2
    restart: unless-stopped
    networks:
      - batserver_docker_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    ports:
      - "3501:3000"    # Changed host port to 30001
    depends_on:
      - influxdb
    volumes:
      - /tank/location/grafana:/var/lib/grafana
    restart: unless-stopped
    networks:
      - batserver_docker_network

volumes:
  location:
    name: location

networks:
  batserver_docker_network:
    external: true
