name: search-tools
services:
  hoarder:
    container_name: Hoarder
    image: ghcr.io/hoarder-app/hoarder:${HOARDER_VERSION:-release}
    restart: unless-stopped
    volumes:
      - /tank/arr/hoarder:/data
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      batserver_docker_network:
    environment:
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      DATA_DIR: /data
      TZ: ${TZ:-Asia/Kolkata}

  chrome:
    container_name: chrome
    image: gcr.io/zenika-hub/alpine-chrome:123
    restart: unless-stopped
    networks:
      batserver_docker_network:
    environment:
      - TZ=${TZ:-Asia/Kolkata}
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars

  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:v1.11.1
    restart: unless-stopped
    env_file:
      - .env
    networks:
      batserver_docker_network:
    environment:
      MEILI_NO_ANALYTICS: "true"
      TZ: ${TZ:-Asia/Kolkata}
    volumes:
      - meilisearch:/meili_data

networks:
  batserver_docker_network:
    external: true

volumes:
  meilisearch:
  data:
